// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHOPxHwpplvHlIVowvg0nCABOKTyU0XyY',
    appId: '1:81036348080:web:fbb7c56b7624f57036c975',
    messagingSenderId: '81036348080',
    projectId: 'deliverymanagement-ce52f',
    authDomain: 'deliverymanagement-ce52f.firebaseapp.com',
    storageBucket: 'deliverymanagement-ce52f.firebasestorage.app',
    measurementId: 'G-6RHDMZGVSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACRmHZuWwoPgp0bHdKEwOUIUxokfYQHbY',
    appId: '1:81036348080:android:b251cc15356bffbf36c975',
    messagingSenderId: '81036348080',
    projectId: 'deliverymanagement-ce52f',
    storageBucket: 'deliverymanagement-ce52f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKu_ztViOf5Oi_R1GLC6eJ5fIZvvz2ysw',
    appId: '1:81036348080:ios:7745b5e180fb496336c975',
    messagingSenderId: '81036348080',
    projectId: 'deliverymanagement-ce52f',
    storageBucket: 'deliverymanagement-ce52f.firebasestorage.app',
    iosBundleId: 'com.example.deliveryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKu_ztViOf5Oi_R1GLC6eJ5fIZvvz2ysw',
    appId: '1:81036348080:ios:7745b5e180fb496336c975',
    messagingSenderId: '81036348080',
    projectId: 'deliverymanagement-ce52f',
    storageBucket: 'deliverymanagement-ce52f.firebasestorage.app',
    iosBundleId: 'com.example.deliveryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHOPxHwpplvHlIVowvg0nCABOKTyU0XyY',
    appId: '1:81036348080:web:4629d6cfe51c9d4736c975',
    messagingSenderId: '81036348080',
    projectId: 'deliverymanagement-ce52f',
    authDomain: 'deliverymanagement-ce52f.firebaseapp.com',
    storageBucket: 'deliverymanagement-ce52f.firebasestorage.app',
    measurementId: 'G-E0SE2JMT9T',
  );
}
